"""
src/ingestion/db.py
===================
Everything that talks to PostgreSQL.

The CREATE TABLE statements are GENERATED from schema.py, so the warehouse
columns and the data columns can never drift apart.

Tables created:
  loan_master        - one row per loan (static fields)
  loan_monthly       - monthly performance time series
  ingestion_log      - one row per file we ingest (audit trail)
  metadata_catalog   - description of every column in the warehouse
"""

from __future__ import annotations

from pathlib import Path

import polars as pl
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from config.settings import settings
from src.ingestion import schema
from src.utils.logger import get_logger

log = get_logger(__name__)


def get_engine() -> Engine:
    """Create a SQLAlchemy engine from the connection string in settings."""
    return create_engine(settings.db_url, pool_pre_ping=True)


def _sql_type(official_col: str) -> str:
    if official_col in schema.DATE_COLUMNS:
        return "DATE"
    if official_col in schema.NUMERIC_COLUMNS:
        return "DOUBLE PRECISION"
    return "TEXT"


def _col_defs(official_cols: list[str]) -> list[str]:
    return [f'    "{schema.db_name(c)}" {_sql_type(c)}' for c in official_cols]


def generate_ddl() -> dict[str, str]:
    """Return the CREATE TABLE statements as a dict {table_name: sql}."""
    master_cols = _col_defs(schema.STATIC_COLUMNS) + ['    "vintage" TEXT']
    monthly_cols = _col_defs(schema.DYNAMIC_COLUMNS) + ['    "vintage" TEXT']

    loan_master = (
        "CREATE TABLE IF NOT EXISTS loan_master (\n"
        '    "loan_id" TEXT PRIMARY KEY,\n'
        + ",\n".join(master_cols)
        + "\n);"
    )
    loan_monthly = (
        "CREATE TABLE IF NOT EXISTS loan_monthly (\n"
        '    "loan_id" TEXT NOT NULL,\n'
        '    "reporting_period" DATE NOT NULL,\n'
        + ",\n".join(monthly_cols)
        + ',\n    PRIMARY KEY ("loan_id", "reporting_period")\n);'
    )
    ingestion_log = (
        "CREATE TABLE IF NOT EXISTS ingestion_log (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    vintage TEXT,\n"
        "    source_file TEXT,\n"
        "    rows_master BIGINT,\n"
        "    rows_monthly BIGINT,\n"
        "    sample_fraction DOUBLE PRECISION,\n"
        "    status TEXT,\n"
        "    message TEXT,\n"
        "    started_at TIMESTAMP DEFAULT now(),\n"
        "    finished_at TIMESTAMP\n"
        ");"
    )
    metadata_catalog = (
        "CREATE TABLE IF NOT EXISTS metadata_catalog (\n"
        "    table_name TEXT,\n"
        "    db_column TEXT,\n"
        "    official_name TEXT,\n"
        "    data_type TEXT,\n"
        "    is_static BOOLEAN,\n"
        "    PRIMARY KEY (table_name, db_column)\n"
        ");"
    )
    return {
        "loan_master": loan_master,
        "loan_monthly": loan_monthly,
        "ingestion_log": ingestion_log,
        "metadata_catalog": metadata_catalog,
    }


def write_schema_sql(path: Path | None = None) -> Path:
    """Write the generated DDL to a .sql file (a project deliverable)."""
    if path is None:
        path = settings.project_root / "sql" / "schema.sql"
    path.parent.mkdir(parents=True, exist_ok=True)
    ddl = generate_ddl()
    body = "-- Auto-generated by src/ingestion/db.py. Do not edit by hand.\n\n"
    body += "\n\n".join(ddl[t] for t in ["loan_master", "loan_monthly", "ingestion_log", "metadata_catalog"])
    path.write_text(body + "\n", encoding="utf-8")
    log.info("Wrote schema DDL to %s", path)
    return path


def create_tables(engine: Engine) -> None:
    """Create all warehouse tables if they do not exist."""
    ddl = generate_ddl()
    with engine.begin() as conn:
        for name, stmt in ddl.items():
            conn.execute(text(stmt))
            log.info("Ensured table: %s", name)


def load_dataframe(df: pl.DataFrame, table: str, engine: Engine,
                   if_exists: str = "append") -> int:
    """Load a Polars dataframe into a table. Returns rows written.

    Uses Polars' write_database (SQLAlchemy backend). For very large loads on
    your machine you can later switch to PostgreSQL COPY for speed; the slower
    path here is portable and correct.
    """
    if df.height == 0:
        log.warning("No rows to load into %s.", table)
        return 0
    df.write_database(
        table_name=table,
        connection=settings.db_url,
        if_table_exists=if_exists,
        engine="sqlalchemy",
    )
    log.info("Loaded %s rows into %s.", f"{df.height:,}", table)
    return df.height


def get_ingested_vintages(engine: Engine) -> set[str]:
    """Return the set of vintages already loaded successfully (for incremental runs)."""
    try:
        with engine.connect() as conn:
            rows = conn.execute(
                text("SELECT DISTINCT vintage FROM ingestion_log WHERE status = 'SUCCESS'")
            ).fetchall()
        return {r[0] for r in rows if r[0] is not None}
    except Exception as exc:  # table may not exist yet on a brand-new database
        log.info("Could not read ingestion_log (%s); treating as no prior ingests.", exc)
        return set()


def delete_vintage(engine: Engine, vintage: str) -> None:
    """Remove any existing rows for one vintage so a reload is idempotent (safe to retry)."""
    with engine.begin() as conn:
        for tbl in ("loan_monthly", "loan_master"):
            conn.execute(text(f"DELETE FROM {tbl} WHERE vintage = :v"), {"v": vintage})
        conn.execute(text("DELETE FROM ingestion_log WHERE vintage = :v"), {"v": vintage})
    log.info("Cleared any existing rows for vintage %s.", vintage)